/*
 *   Copyright (C) 2006-2007 Jiri Majer. All Rights Reserved.
 *   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 *   This code is free software; you can redistribute it and/or modify it
 *   under the terms of the GNU General Public License version 2 only, as
 *   published by the Free Software Foundation.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program; if not, write to the Free Software
 *   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
package org.diabetesdiary.commons.swing.calendar;

import javax.swing.JFileChooser;
import javax.swing.plaf.FileChooserUI;
import org.joda.time.DateTime;

/**
 *
 * @author Jirka Majer
 */
public class DateTimePanel extends javax.swing.JPanel {

    /** Creates new form DateTimePanel */
    public DateTimePanel() {
        this(null);
    }

    public DateTimePanel(DateTime dateTime) {
        initComponents();
        setDateTime(dateTime == null ? new DateTime() : dateTime);
    }

    public void setDateTime(DateTime dateTime) {
        dateJSpinner1.setDateTime(dateTime);
        timeJSpinner1.setDateTime(dateTime);
    }

    public DateTime getDateTime() {
        DateTime time = timeJSpinner1.getDateTime();
        return dateJSpinner1.getDateTime().withTime(time.getHourOfDay(), time.getMinuteOfHour(), 0, 0);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateTimePicker1 = new org.diabetesdiary.commons.swing.calendar.DateTimePicker();
        timeJSpinner1 = new org.diabetesdiary.commons.swing.calendar.TimeJSpinner();
        dateJSpinner1 = new org.diabetesdiary.commons.swing.calendar.DateJSpinner();
        jButton1 = new javax.swing.JButton();

        setLayout(null);
        add(timeJSpinner1);
        timeJSpinner1.setBounds(79, 0, 51, 20);
        add(dateJSpinner1);
        dateJSpinner1.setBounds(0, 0, 73, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/diabetesdiary/commons/swing/calendar/JCalendarColor32.gif"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(130, 0, 33, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DateTime newDate = dateTimePicker1.getDateTimeFromUser(dateJSpinner1.getDateTime());
        if (newDate != null) {
            dateJSpinner1.setDateTime(newDate);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.diabetesdiary.commons.swing.calendar.DateJSpinner dateJSpinner1;
    private org.diabetesdiary.commons.swing.calendar.DateTimePicker dateTimePicker1;
    private javax.swing.JButton jButton1;
    private org.diabetesdiary.commons.swing.calendar.TimeJSpinner timeJSpinner1;
    // End of variables declaration//GEN-END:variables
}
